/*
 * Kitsune Boot - Boot Animation Maker for Android
 * Copyright (C) 2026 Yervant
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package com.yervant.kitsuneboot

import java.io.BufferedOutputStream
import java.io.ByteArrayInputStream
import java.io.File
import java.io.OutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object MagiskModuleGenerator {

    /**
     * Packages an already generated bootanimation.zip file into a flashable Magisk/KernelSU/APatch module zip.
     */
    fun createModule(
        bootAnimFile: File,
        moduleName: String,
        moduleAuthor: String,
        outputStream: OutputStream
    ) {
        val sanitizedId = moduleName.lowercase()
            .replace("[^a-z0-9_]".toRegex(), "_")
            .ifEmpty { "custom_bootanimation" }

        val modulePropContent = buildString {
            append("id=$sanitizedId\n")
            append("name=$moduleName\n")
            append("version=1.0\n")
            append("versionCode=1\n")
            append("author=$moduleAuthor\n")
            append("description=Boot Animation generated by https://github.com/Yervant7/KitsuneBoot\n")
        }

        val customizeShContent = buildString {
            append("SKIPUNZIP=0\n")
            append("ui_print \"- Installing Custom Boot Animation\"\n")
            append("ui_print \"! WARNING: Incorrect boot animation configs may cause bootloops\"\n")
            append("ui_print \"! Ensure your device supports the chosen resolution and format\"\n\n")
            append("# Detect partition structure and symlinks to avoid duplicate files or broken symlinks\n")
            append("TARGET_DIR=\"\"\n")
            append("if [ -L \"/system/media\" ] || [ -L \"/system/system/media\" ]; then\n")
            append("  SYMLINK_TARGET=\$(readlink /system/media 2>/dev/null || readlink /system/system/media 2>/dev/null)\n")
            append("  ui_print \"- Detected /system/media as symlink -> \$SYMLINK_TARGET\"\n")
            append("  if [ -d \"/product/media\" ] || [ -d \"/system/product/media\" ] || echo \"\$SYMLINK_TARGET\" | grep -q \"product\"; then\n")
            append("    TARGET_DIR=\"\$MODPATH/system/product/media\"\n")
            append("  elif [ -d \"/system_ext/media\" ] || [ -d \"/system/system_ext/media\" ] || echo \"\$SYMLINK_TARGET\" | grep -q \"system_ext\"; then\n")
            append("    TARGET_DIR=\"\$MODPATH/system/system_ext/media\"\n")
            append("  else\n")
            append("    TARGET_DIR=\"\$MODPATH/system/product/media\"\n")
            append("  fi\n")
            append("elif [ -L \"/product/media\" ] || [ -L \"/system/product/media\" ]; then\n")
            append("  ui_print \"- Detected /product/media as symlink\"\n")
            append("  TARGET_DIR=\"\$MODPATH/system/media\"\n")
            append("elif [ -f \"/product/media/bootanimation.zip\" ] || [ -f \"/system/product/media/bootanimation.zip\" ]; then\n")
            append("  ui_print \"- Detected stock bootanimation in product/media\"\n")
            append("  TARGET_DIR=\"\$MODPATH/system/product/media\"\n")
            append("elif [ -f \"/system_ext/media/bootanimation.zip\" ] || [ -f \"/system/system_ext/media/bootanimation.zip\" ]; then\n")
            append("  ui_print \"- Detected stock bootanimation in system_ext/media\"\n")
            append("  TARGET_DIR=\"\$MODPATH/system/system_ext/media\"\n")
            append("elif [ -f \"/system/media/bootanimation.zip\" ] || [ -f \"/system/system/media/bootanimation.zip\" ]; then\n")
            append("  ui_print \"- Detected stock bootanimation in system/media\"\n")
            append("  TARGET_DIR=\"\$MODPATH/system/media\"\n")
            append("elif [ -d \"/product/media\" ] || [ -d \"/system/product/media\" ]; then\n")
            append("  ui_print \"- Detected product/media directory\"\n")
            append("  TARGET_DIR=\"\$MODPATH/system/product/media\"\n")
            append("else\n")
            append("  ui_print \"- Using default /system/media\"\n")
            append("  TARGET_DIR=\"\$MODPATH/system/media\"\n")
            append("fi\n\n")
            append("ui_print \"- Target: \$TARGET_DIR/bootanimation.zip\"\n")
            append("mkdir -p \"\$TARGET_DIR\"\n")
            append("mv \"\$MODPATH/bootanimation.zip\" \"\$TARGET_DIR/bootanimation.zip\"\n")
            append("rm -f \"\$MODPATH/bootanimation.zip\"\n\n")
            append("set_perm_recursive \"\$MODPATH\" 0 0 0755 0644\n")
            append("set_perm \"\$TARGET_DIR/bootanimation.zip\" 0 0 0644\n")
        }

        ZipOutputStream(BufferedOutputStream(outputStream)).use { zipOut ->
            // 1. Add module.prop
            addTextEntry(zipOut, "module.prop", modulePropContent)

            // 2. Add customize.sh
            addTextEntry(zipOut, "customize.sh", customizeShContent)

            // 3. Add bootanimation.zip (single copy, dynamically placed by customize.sh)
            addFileEntry(zipOut, "bootanimation.zip", bootAnimFile)
        }
    }

    private fun addTextEntry(zipOut: ZipOutputStream, entryName: String, content: String) {
        val bytes = content.toByteArray(Charsets.UTF_8)
        val entry = ZipEntry(entryName).apply {
            size = bytes.size.toLong()
        }
        zipOut.putNextEntry(entry)
        ByteArrayInputStream(bytes).copyTo(zipOut)
        zipOut.closeEntry()
    }

    private fun addFileEntry(zipOut: ZipOutputStream, entryName: String, file: File) {
        val entry = ZipEntry(entryName).apply {
            size = file.length()
        }
        zipOut.putNextEntry(entry)
        file.inputStream().buffered().use { input ->
            input.copyTo(zipOut)
        }
        zipOut.closeEntry()
    }
}
